"""GitHub MCP adapter stub."""

from __future__ import annotations

from typing import Any, Dict

from devops_brain.mcp.base import MCPActionResult, MCPAdapter


class GitHubAdapter(MCPAdapter):
    """Triggers GitHub Actions workflows or posts issues."""

    def action_dispatch_workflow(self, payload: Dict[str, Any]) -> MCPActionResult:
        workflow = payload.get("workflow") or self.config.settings.get("workflow")
        repo = payload.get("repo") or self.config.settings.get("repo")

        message = f"Dispatched workflow '{workflow}' on repo '{repo}'."
        self.logger.info(message)
        return MCPActionResult(
            name=self.name,
            success=True,
            message=message,
            details={"workflow": workflow, "repo": repo, "inputs": payload.get("inputs", {})},
        )

    def action_open_issue(self, payload: Dict[str, Any]) -> MCPActionResult:
        title = payload.get("title", "Automated issue")
        body = payload.get("body", "Generated by DevOps Brain.")
        repo = payload.get("repo") or self.config.settings.get("repo")
        message = f"Opened issue '{title}' in {repo}."
        self.logger.info(message)
        return MCPActionResult(
            name=self.name,
            success=True,
            message=message,
            details={"title": title, "body": body, "repo": repo},
        )
